name: 'Test'
on: [ push, pull_request, workflow_dispatch ]
jobs:
  lint:
    name: 'Static code analysis'
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable
    steps:
    - uses: actions/checkout@v3
    - run: flutter --version
    - run: flutter pub get
    # Use this commit till there is a new release that uses Node 16
    - uses: invertase/github-action-dart-analyzer@1cda5922c6369263b1c7e2fbe281f69704f4d63e
      with:
        fatal-infos: true
        fatal-warnings: true

  test:
    name: 'Unit tests'
    if: '${{false}}'                   # disabled for now
    runs-on: ubuntu-latest
    container: cirrusci/flutter:stable
    steps:
    - uses: actions/checkout@v3
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
